# Dependabot configuration
# See https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/customizing-dependency-updates
version: 2
updates:
  - package-ecosystem: 'nuget'
    directory: '/'
    schedule:
      interval: 'monthly'
      time: '16:00'
    # Update every library in one PR
    groups:
      all:
        patterns:
          - '*'
        update-types:
          - 'minor'
          - 'patch'
